// Mocks generated by Mockito 5.4.6 from annotations
// in promodo_study/test/coordinators/timer_coordinator_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:promodo_study/core/interfaces.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [IAudioService].
///
/// See the documentation for Mockito's code generation for more information.
class MockIAudioService extends _i1.Mock implements _i2.IAudioService {
  MockIAudioService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isEnabled =>
      (super.noSuchMethod(Invocation.getter(#isEnabled), returnValue: false)
          as bool);

  @override
  void setEnabled(bool? enabled) => super.noSuchMethod(
    Invocation.method(#setEnabled, [enabled]),
    returnValueForMissingStub: null,
  );

  @override
  _i3.Future<void> playStudyStart() =>
      (super.noSuchMethod(
            Invocation.method(#playStudyStart, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> playStudyComplete() =>
      (super.noSuchMethod(
            Invocation.method(#playStudyComplete, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> playBreakStart() =>
      (super.noSuchMethod(
            Invocation.method(#playBreakStart, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> playBreakComplete() =>
      (super.noSuchMethod(
            Invocation.method(#playBreakComplete, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> playCycleComplete() =>
      (super.noSuchMethod(
            Invocation.method(#playCycleComplete, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> playBackgroundMusic() =>
      (super.noSuchMethod(
            Invocation.method(#playBackgroundMusic, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> stopBackgroundMusic() =>
      (super.noSuchMethod(
            Invocation.method(#stopBackgroundMusic, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}

/// A class which mocks [INotificationService].
///
/// See the documentation for Mockito's code generation for more information.
class MockINotificationService extends _i1.Mock
    implements _i2.INotificationService {
  MockINotificationService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> init() =>
      (super.noSuchMethod(
            Invocation.method(#init, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> showStudyStartNotification() =>
      (super.noSuchMethod(
            Invocation.method(#showStudyStartNotification, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> showStudyCompleteNotification() =>
      (super.noSuchMethod(
            Invocation.method(#showStudyCompleteNotification, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> showBreakStartNotification() =>
      (super.noSuchMethod(
            Invocation.method(#showBreakStartNotification, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> showBreakCompleteNotification() =>
      (super.noSuchMethod(
            Invocation.method(#showBreakCompleteNotification, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> showCycleCompleteNotification(int? cycles) =>
      (super.noSuchMethod(
            Invocation.method(#showCycleCompleteNotification, [cycles]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> cancelAll() =>
      (super.noSuchMethod(
            Invocation.method(#cancelAll, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}

/// A class which mocks [IWidgetService].
///
/// See the documentation for Mockito's code generation for more information.
class MockIWidgetService extends _i1.Mock implements _i2.IWidgetService {
  MockIWidgetService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> init() =>
      (super.noSuchMethod(
            Invocation.method(#init, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> updateTimer({
    required bool? isRunning,
    required int? remainingSeconds,
    required String? sessionType,
    required String? themeName,
    String? taskName,
    double? progress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateTimer, [], {
              #isRunning: isRunning,
              #remainingSeconds: remainingSeconds,
              #sessionType: sessionType,
              #themeName: themeName,
              #taskName: taskName,
              #progress: progress,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> updateStatistics({
    required int? todayPomodoros,
    required int? todayMinutes,
    required int? currentStreak,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateStatistics, [], {
              #todayPomodoros: todayPomodoros,
              #todayMinutes: todayMinutes,
              #currentStreak: currentStreak,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> clearAll() =>
      (super.noSuchMethod(
            Invocation.method(#clearAll, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}
